/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HospitalAppointmentSystem;

import javax.swing.JFrame;

/**
 *
 * @author Özlem
 */
public class DateandTime extends javax.swing.JFrame {

    /**
     * Creates new form DateandTime
     */
    public DateandTime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLoginButton20 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jOKButton = new javax.swing.JButton();
        jLoginButton1 = new javax.swing.JButton();
        jLoginButton2 = new javax.swing.JButton();
        jLoginButton3 = new javax.swing.JButton();
        jLoginButton4 = new javax.swing.JButton();
        jLoginButton5 = new javax.swing.JButton();
        jLoginButton6 = new javax.swing.JButton();
        jLoginButton7 = new javax.swing.JButton();
        jLoginButton8 = new javax.swing.JButton();
        jLoginButton9 = new javax.swing.JButton();
        jLoginButton10 = new javax.swing.JButton();
        jLoginButton11 = new javax.swing.JButton();
        jLoginButton12 = new javax.swing.JButton();
        jLoginButton13 = new javax.swing.JButton();
        jLoginButton14 = new javax.swing.JButton();
        jLoginButton15 = new javax.swing.JButton();
        jLoginButton16 = new javax.swing.JButton();
        jLoginButton17 = new javax.swing.JButton();
        jLoginButton18 = new javax.swing.JButton();
        jLoginButton19 = new javax.swing.JButton();
        jLoginButton21 = new javax.swing.JButton();
        jLoginButton22 = new javax.swing.JButton();
        jLoginButton23 = new javax.swing.JButton();
        jLoginButton24 = new javax.swing.JButton();
        jLoginButton25 = new javax.swing.JButton();
        jLoginButton26 = new javax.swing.JButton();
        jLoginButton27 = new javax.swing.JButton();
        jLoginButton28 = new javax.swing.JButton();
        jLoginButton29 = new javax.swing.JButton();
        jLoginButton30 = new javax.swing.JButton();
        jLoginButton31 = new javax.swing.JButton();
        jLoginButton32 = new javax.swing.JButton();
        jLoginButton33 = new javax.swing.JButton();
        jLoginButton34 = new javax.swing.JButton();
        jLoginButton35 = new javax.swing.JButton();
        jLoginButton36 = new javax.swing.JButton();
        jLoginButton37 = new javax.swing.JButton();
        jLoginButton38 = new javax.swing.JButton();
        jLoginButton39 = new javax.swing.JButton();
        jLoginButton40 = new javax.swing.JButton();
        jLoginButton41 = new javax.swing.JButton();
        jLoginButton42 = new javax.swing.JButton();
        jLoginButton43 = new javax.swing.JButton();

        jLoginButton20.setBackground(new java.awt.Color(34, 167, 240));
        jLoginButton20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton20.setText("16:00");
        jLoginButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton20MouseClicked(evt);
            }
        });
        jLoginButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton20ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jComboBox1.setBackground(new java.awt.Color(108, 122, 137));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a date", "01/04/2020", "02/04/2020", "03/04/2020", "04/04/2020", "05/04/2020", "06/04/2020", "07/04/2020", "08/04/2020", "09/04/2020", "10/04/2020", "11/04/2020", "12/04/2020", "13/04/2020", "14/04/2020", "15/04/2020", "16/04/2020", "17/04/2020", "18/04/2020", "19/04/2020", "20/04/2020", "21/04/2020", "22/04/2020", "23/04/2020", "24/04/2020", "25/04/2020", "26/04/2020", "27/04/2020", "28/04/2020", "29/04/2020", "30/04/2020" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jComboBox2.setBackground(new java.awt.Color(108, 122, 137));
        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a date", "01/05/2020", "02/05/2020", "03/05/2020", "04/05/2020", "05/05/2020", "06/05/2020", "07/05/2020", "08/05/2020", "09/05/2020", "10/05/2020", "11/05/2020", "12/05/2020", "13/05/2020", "14/05/2020", "15/05/2020", "16/05/2020", "17/05/2020", "18/05/2020", "19/05/2020", "20/05/2020", "21/05/2020", "22/05/2020", "23/05/2020", "24/05/2020", "25/05/2020", "26/05/2020", "27/05/2020", "28/05/2020", "29/05/2020", "30/05/2020", "31/05/2020" }));

        jComboBox3.setBackground(new java.awt.Color(108, 122, 137));
        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a date", "01/06/2020", "02/06/2020", "03/06/2020", "04/06/2020", "05/06/2020", "06/06/2020", "07/06/2020", "08/06/2020", "09/06/2020", "10/06/2020", "11/06/2020", "12/06/2020", "13/06/2020", "14/06/2020", "15/06/2020", "16/06/2020", "17/06/2020", "18/06/2020", "19/06/2020", "20/06/2020", "21/06/2020", "22/06/2020", "23/06/2020", "24/06/2020", "25/06/2020", "26/06/2020", "27/06/2020", "28/06/2020", "29/06/2020", "30/06/2020" }));

        jOKButton.setBackground(new java.awt.Color(34, 167, 240));
        jOKButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jOKButton.setText("OK");
        jOKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOKButtonMouseClicked(evt);
            }
        });
        jOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKButtonActionPerformed(evt);
            }
        });

        jLoginButton1.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton1.setText("09:00");
        jLoginButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton1MouseClicked(evt);
            }
        });
        jLoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton1ActionPerformed(evt);
            }
        });

        jLoginButton2.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton2.setText("10:00");
        jLoginButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton2MouseClicked(evt);
            }
        });
        jLoginButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton2ActionPerformed(evt);
            }
        });

        jLoginButton3.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton3.setText("09:00");
        jLoginButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton3MouseClicked(evt);
            }
        });
        jLoginButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton3ActionPerformed(evt);
            }
        });

        jLoginButton4.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton4.setText("10:30");
        jLoginButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton4MouseClicked(evt);
            }
        });
        jLoginButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton4ActionPerformed(evt);
            }
        });

        jLoginButton5.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton5.setText("09:30");
        jLoginButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton5MouseClicked(evt);
            }
        });
        jLoginButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton5ActionPerformed(evt);
            }
        });

        jLoginButton6.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton6.setText("10:30");
        jLoginButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton6MouseClicked(evt);
            }
        });
        jLoginButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton6ActionPerformed(evt);
            }
        });

        jLoginButton7.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton7.setText("14:30");
        jLoginButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton7MouseClicked(evt);
            }
        });
        jLoginButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton7ActionPerformed(evt);
            }
        });

        jLoginButton8.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton8.setText("13:00");
        jLoginButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton8MouseClicked(evt);
            }
        });
        jLoginButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton8ActionPerformed(evt);
            }
        });

        jLoginButton9.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton9.setText("11:00");
        jLoginButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton9MouseClicked(evt);
            }
        });
        jLoginButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton9ActionPerformed(evt);
            }
        });

        jLoginButton10.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton10.setText("16:30");
        jLoginButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton10MouseClicked(evt);
            }
        });
        jLoginButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton10ActionPerformed(evt);
            }
        });

        jLoginButton11.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton11.setText("11:30");
        jLoginButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton11MouseClicked(evt);
            }
        });
        jLoginButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton11ActionPerformed(evt);
            }
        });

        jLoginButton12.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton12.setText("13:00");
        jLoginButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton12MouseClicked(evt);
            }
        });
        jLoginButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton12ActionPerformed(evt);
            }
        });

        jLoginButton13.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton13.setText("13:30");
        jLoginButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton13MouseClicked(evt);
            }
        });
        jLoginButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton13ActionPerformed(evt);
            }
        });

        jLoginButton14.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton14.setText("14:00");
        jLoginButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton14MouseClicked(evt);
            }
        });
        jLoginButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton14ActionPerformed(evt);
            }
        });

        jLoginButton15.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton15.setText("14:30");
        jLoginButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton15MouseClicked(evt);
            }
        });
        jLoginButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton15ActionPerformed(evt);
            }
        });

        jLoginButton16.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton16.setText("15:30");
        jLoginButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton16MouseClicked(evt);
            }
        });
        jLoginButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton16ActionPerformed(evt);
            }
        });

        jLoginButton17.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton17.setText("15:00");
        jLoginButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton17MouseClicked(evt);
            }
        });
        jLoginButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton17ActionPerformed(evt);
            }
        });

        jLoginButton18.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton18.setText("16:00");
        jLoginButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton18MouseClicked(evt);
            }
        });
        jLoginButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton18ActionPerformed(evt);
            }
        });

        jLoginButton19.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton19.setText("16:00");
        jLoginButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton19MouseClicked(evt);
            }
        });
        jLoginButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton19ActionPerformed(evt);
            }
        });

        jLoginButton21.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton21.setText("11:00");
        jLoginButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton21MouseClicked(evt);
            }
        });
        jLoginButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton21ActionPerformed(evt);
            }
        });

        jLoginButton22.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton22.setText("09:15");
        jLoginButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton22MouseClicked(evt);
            }
        });
        jLoginButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton22ActionPerformed(evt);
            }
        });

        jLoginButton23.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton23.setText("13:30");
        jLoginButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton23MouseClicked(evt);
            }
        });
        jLoginButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton23ActionPerformed(evt);
            }
        });

        jLoginButton24.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton24.setText("15:00");
        jLoginButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton24MouseClicked(evt);
            }
        });
        jLoginButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton24ActionPerformed(evt);
            }
        });

        jLoginButton25.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton25.setText("16:30");
        jLoginButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton25MouseClicked(evt);
            }
        });
        jLoginButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton25ActionPerformed(evt);
            }
        });

        jLoginButton26.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton26.setText("10:00");
        jLoginButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton26MouseClicked(evt);
            }
        });
        jLoginButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton26ActionPerformed(evt);
            }
        });

        jLoginButton27.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton27.setText("11:30");
        jLoginButton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton27MouseClicked(evt);
            }
        });
        jLoginButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton27ActionPerformed(evt);
            }
        });

        jLoginButton28.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton28.setText("14:00");
        jLoginButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton28MouseClicked(evt);
            }
        });
        jLoginButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton28ActionPerformed(evt);
            }
        });

        jLoginButton29.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton29.setText("15:30");
        jLoginButton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton29MouseClicked(evt);
            }
        });
        jLoginButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton29ActionPerformed(evt);
            }
        });

        jLoginButton30.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton30.setText("09:00");
        jLoginButton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton30MouseClicked(evt);
            }
        });
        jLoginButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton30ActionPerformed(evt);
            }
        });

        jLoginButton31.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton31.setText("10:30");
        jLoginButton31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton31MouseClicked(evt);
            }
        });
        jLoginButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton31ActionPerformed(evt);
            }
        });

        jLoginButton32.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton32.setText("13:00");
        jLoginButton32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton32MouseClicked(evt);
            }
        });
        jLoginButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton32ActionPerformed(evt);
            }
        });

        jLoginButton33.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton33.setText("14:30");
        jLoginButton33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton33MouseClicked(evt);
            }
        });
        jLoginButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton33ActionPerformed(evt);
            }
        });

        jLoginButton34.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton34.setText("16:00");
        jLoginButton34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton34MouseClicked(evt);
            }
        });
        jLoginButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton34ActionPerformed(evt);
            }
        });

        jLoginButton35.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton35.setText("09:15");
        jLoginButton35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton35MouseClicked(evt);
            }
        });
        jLoginButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton35ActionPerformed(evt);
            }
        });

        jLoginButton36.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton36.setText("11:00");
        jLoginButton36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton36MouseClicked(evt);
            }
        });
        jLoginButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton36ActionPerformed(evt);
            }
        });

        jLoginButton37.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton37.setText("13:30");
        jLoginButton37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton37MouseClicked(evt);
            }
        });
        jLoginButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton37ActionPerformed(evt);
            }
        });

        jLoginButton38.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton38.setText("15:00");
        jLoginButton38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton38MouseClicked(evt);
            }
        });
        jLoginButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton38ActionPerformed(evt);
            }
        });

        jLoginButton39.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton39.setText("10:00");
        jLoginButton39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton39MouseClicked(evt);
            }
        });
        jLoginButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton39ActionPerformed(evt);
            }
        });

        jLoginButton40.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton40.setText("11:30");
        jLoginButton40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton40MouseClicked(evt);
            }
        });
        jLoginButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton40ActionPerformed(evt);
            }
        });

        jLoginButton41.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton41.setText("14:00");
        jLoginButton41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton41MouseClicked(evt);
            }
        });
        jLoginButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton41ActionPerformed(evt);
            }
        });

        jLoginButton42.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton42.setText("15:30");
        jLoginButton42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton42MouseClicked(evt);
            }
        });
        jLoginButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton42ActionPerformed(evt);
            }
        });

        jLoginButton43.setBackground(new java.awt.Color(236, 240, 241));
        jLoginButton43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoginButton43.setText("16:30");
        jLoginButton43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButton43MouseClicked(evt);
            }
        });
        jLoginButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton43ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLoginButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLoginButton2))
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLoginButton15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLoginButton16))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLoginButton6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLoginButton11))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLoginButton12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLoginButton14))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLoginButton18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton10))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLoginButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton26))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLoginButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton27))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLoginButton8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton28))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLoginButton7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton29))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLoginButton19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton25))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLoginButton30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton35)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton39))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLoginButton31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton36)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLoginButton40))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLoginButton32)
                                .addComponent(jLoginButton33)
                                .addComponent(jLoginButton34, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLoginButton37)
                                    .addComponent(jLoginButton38))
                                .addComponent(jLoginButton43))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLoginButton41)
                                .addComponent(jLoginButton42)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton1)
                    .addComponent(jLoginButton5)
                    .addComponent(jLoginButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton6)
                    .addComponent(jLoginButton9)
                    .addComponent(jLoginButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton12)
                    .addComponent(jLoginButton13)
                    .addComponent(jLoginButton14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton15)
                    .addComponent(jLoginButton17)
                    .addComponent(jLoginButton16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton18)
                    .addComponent(jLoginButton10))
                .addGap(28, 28, 28)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton3)
                    .addComponent(jLoginButton22)
                    .addComponent(jLoginButton26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton4)
                    .addComponent(jLoginButton21)
                    .addComponent(jLoginButton27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton8)
                    .addComponent(jLoginButton23)
                    .addComponent(jLoginButton28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLoginButton24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLoginButton7)
                        .addComponent(jLoginButton29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton19)
                    .addComponent(jLoginButton25))
                .addGap(34, 34, 34)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton30)
                    .addComponent(jLoginButton35)
                    .addComponent(jLoginButton39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton36)
                    .addComponent(jLoginButton31)
                    .addComponent(jLoginButton40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton37)
                    .addComponent(jLoginButton32)
                    .addComponent(jLoginButton41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton38)
                    .addComponent(jLoginButton33)
                    .addComponent(jLoginButton42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton34)
                    .addComponent(jLoginButton43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jOKButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOKButtonMouseClicked
        // TODO add your handling code here:
        ConfirmationScreen cs = new ConfirmationScreen();
        cs.setVisible(true);
        cs.pack();
        cs.setLocationRelativeTo(null);
        cs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jOKButtonMouseClicked

    private void jOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOKButtonActionPerformed

    private void jLoginButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton1MouseClicked

    private void jLoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton1ActionPerformed

    private void jLoginButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton2MouseClicked

    private void jLoginButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton2ActionPerformed

    private void jLoginButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton3MouseClicked

    private void jLoginButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton3ActionPerformed

    private void jLoginButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton4MouseClicked

    private void jLoginButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton4ActionPerformed

    private void jLoginButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton5MouseClicked

    private void jLoginButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton5ActionPerformed

    private void jLoginButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton6MouseClicked

    private void jLoginButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton6ActionPerformed

    private void jLoginButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton7MouseClicked

    private void jLoginButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton7ActionPerformed

    private void jLoginButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton8MouseClicked

    private void jLoginButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton8ActionPerformed

    private void jLoginButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton9MouseClicked

    private void jLoginButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton9ActionPerformed

    private void jLoginButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton10MouseClicked

    private void jLoginButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton10ActionPerformed

    private void jLoginButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton11MouseClicked

    private void jLoginButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton11ActionPerformed

    private void jLoginButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton12MouseClicked

    private void jLoginButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton12ActionPerformed

    private void jLoginButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton13MouseClicked

    private void jLoginButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton13ActionPerformed

    private void jLoginButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton14MouseClicked

    private void jLoginButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton14ActionPerformed

    private void jLoginButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton15MouseClicked

    private void jLoginButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton15ActionPerformed

    private void jLoginButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton16MouseClicked

    private void jLoginButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton16ActionPerformed

    private void jLoginButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton17MouseClicked

    private void jLoginButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton17ActionPerformed

    private void jLoginButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton18MouseClicked

    private void jLoginButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton18ActionPerformed

    private void jLoginButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton19MouseClicked

    private void jLoginButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton19ActionPerformed

    private void jLoginButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton20MouseClicked

    private void jLoginButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton20ActionPerformed

    private void jLoginButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton21MouseClicked

    private void jLoginButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton21ActionPerformed

    private void jLoginButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton22MouseClicked

    private void jLoginButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton22ActionPerformed

    private void jLoginButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton23MouseClicked

    private void jLoginButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton23ActionPerformed

    private void jLoginButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton24MouseClicked

    private void jLoginButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton24ActionPerformed

    private void jLoginButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton25MouseClicked

    private void jLoginButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton25ActionPerformed

    private void jLoginButton26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton26MouseClicked

    private void jLoginButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton26ActionPerformed

    private void jLoginButton27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton27MouseClicked

    private void jLoginButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton27ActionPerformed

    private void jLoginButton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton28MouseClicked

    private void jLoginButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton28ActionPerformed

    private void jLoginButton29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton29MouseClicked

    private void jLoginButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton29ActionPerformed

    private void jLoginButton30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton30MouseClicked

    private void jLoginButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton30ActionPerformed

    private void jLoginButton31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton31MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton31MouseClicked

    private void jLoginButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton31ActionPerformed

    private void jLoginButton32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton32MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton32MouseClicked

    private void jLoginButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton32ActionPerformed

    private void jLoginButton33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton33MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton33MouseClicked

    private void jLoginButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton33ActionPerformed

    private void jLoginButton34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton34MouseClicked

    private void jLoginButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton34ActionPerformed

    private void jLoginButton35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton35MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton35MouseClicked

    private void jLoginButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton35ActionPerformed

    private void jLoginButton36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton36MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton36MouseClicked

    private void jLoginButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton36ActionPerformed

    private void jLoginButton37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton37MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton37MouseClicked

    private void jLoginButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton37ActionPerformed

    private void jLoginButton38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton38MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton38MouseClicked

    private void jLoginButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton38ActionPerformed

    private void jLoginButton39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton39MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton39MouseClicked

    private void jLoginButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton39ActionPerformed

    private void jLoginButton40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton40MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton40MouseClicked

    private void jLoginButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton40ActionPerformed

    private void jLoginButton41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton41MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton41MouseClicked

    private void jLoginButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton41ActionPerformed

    private void jLoginButton42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton42MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton42MouseClicked

    private void jLoginButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton42ActionPerformed

    private void jLoginButton43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButton43MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton43MouseClicked

    private void jLoginButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginButton43ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DateandTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DateandTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DateandTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DateandTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DateandTime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JButton jLoginButton1;
    private javax.swing.JButton jLoginButton10;
    private javax.swing.JButton jLoginButton11;
    private javax.swing.JButton jLoginButton12;
    private javax.swing.JButton jLoginButton13;
    private javax.swing.JButton jLoginButton14;
    private javax.swing.JButton jLoginButton15;
    private javax.swing.JButton jLoginButton16;
    private javax.swing.JButton jLoginButton17;
    private javax.swing.JButton jLoginButton18;
    private javax.swing.JButton jLoginButton19;
    private javax.swing.JButton jLoginButton2;
    private javax.swing.JButton jLoginButton20;
    private javax.swing.JButton jLoginButton21;
    private javax.swing.JButton jLoginButton22;
    private javax.swing.JButton jLoginButton23;
    private javax.swing.JButton jLoginButton24;
    private javax.swing.JButton jLoginButton25;
    private javax.swing.JButton jLoginButton26;
    private javax.swing.JButton jLoginButton27;
    private javax.swing.JButton jLoginButton28;
    private javax.swing.JButton jLoginButton29;
    private javax.swing.JButton jLoginButton3;
    private javax.swing.JButton jLoginButton30;
    private javax.swing.JButton jLoginButton31;
    private javax.swing.JButton jLoginButton32;
    private javax.swing.JButton jLoginButton33;
    private javax.swing.JButton jLoginButton34;
    private javax.swing.JButton jLoginButton35;
    private javax.swing.JButton jLoginButton36;
    private javax.swing.JButton jLoginButton37;
    private javax.swing.JButton jLoginButton38;
    private javax.swing.JButton jLoginButton39;
    private javax.swing.JButton jLoginButton4;
    private javax.swing.JButton jLoginButton40;
    private javax.swing.JButton jLoginButton41;
    private javax.swing.JButton jLoginButton42;
    private javax.swing.JButton jLoginButton43;
    private javax.swing.JButton jLoginButton5;
    private javax.swing.JButton jLoginButton6;
    private javax.swing.JButton jLoginButton7;
    private javax.swing.JButton jLoginButton8;
    private javax.swing.JButton jLoginButton9;
    private javax.swing.JButton jOKButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
